
url: https://jaorduz.github.io 
repository: "https://jaorduz.github.io"
permalink: https://jaorduz.github.io
title: JO's Courses
author: Javier Orduz
show_downloads: false 
theme: jekyll-theme-minimal
date_format: "%B %-d, %Y"
markdown: kramdown
# JAOD
plugins:
  - jemoji
