# Site Settings
locale                   : "en-US"
title                    : "Researcher and professor"
title_separator          : "-"
description              : &description "personal description"
url                      : https://jaorduz.github.io 
repository               : "https://jaorduz.github.io"

